services:
  text-similarity:
    build:
      context: .
      args:
        SENTENCE_TRANSFORMER_MODEL: ${SENTENCE_TRANSFORMER_MODEL:-all-MiniLM-L6-v2}
    ports:
      - "44101:44101"
    depends_on:
      - ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:44101/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
